package com.hyperbrain.sync.domain.model;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Domain record representing a row in {@code core_executable}. Covers only the fields
 * written by the sync pipeline; other columns use their DDL defaults or remain null.
 *
 * @param id             surrogate key; generated by the handler before persist
 * @param userId         owning user (single-user MVP; injected from config)
 * @param name           human-readable name ({@code core_executable.name})
 * @param description    optional free text; carries the EventKit {@code notes} field
 * @param type           executable type: {@code TASK} for reminders, {@code ACTIVITY} for events
 * @param status         lifecycle status: {@code DONE} if completed, {@code TODO} otherwise
 * @param startTime      optional start timestamp (calendar events)
 * @param endTime        optional end / due timestamp
 * @param sourceCalendar list or calendar name the entity came from
 */
public record CoreExecutable(
    UUID id,
    UUID userId,
    String name,
    String description,
    String type,
    String status,
    OffsetDateTime startTime,
    OffsetDateTime endTime,
    String sourceCalendar
) {
}
