package com.hyperbrain.sync.domain.model;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Domain record representing a row in {@code core_executable}. Covers the fields written by the
 * sync pipeline plus the two the pipeline only ever <em>reads</em> to decide whether a row is
 * written back at all ({@code systemGenerated}, {@code origin}); every other column keeps its DDL
 * default or stays null.
 *
 * @param id             surrogate key; generated by the handler before persist
 * @param userId         owning user (single-user MVP; injected from config)
 * @param name           human-readable name ({@code core_executable.name})
 * @param description    optional free text; carries the EventKit {@code notes} field
 * @param type           executable type: {@code TASK} for reminders, {@code ACTIVITY} for events
 * @param status         lifecycle status: {@code DONE} if completed, {@code TODO} otherwise
 * @param startTime       optional start timestamp (calendar events)
 * @param endTime         optional end / due timestamp
 * @param sourceCalendar  list or calendar name the entity came from
 * @param systemGenerated true for internal accounting rows (e.g. focus-switch snapshot subtasks,
 *                        ADR-013 DR-06); such rows are never written back to external systems
 * @param origin          who authored the row ({@code PLANNER}, {@code FOCUS}, {@code USER}), null
 *                        for everything the user or a satellite created; read-only here, like
 *                        {@code systemGenerated} — the sync pipeline never writes it
 */
public record CoreExecutable(
    UUID id,
    UUID userId,
    String name,
    String description,
    String type,
    String status,
    OffsetDateTime startTime,
    OffsetDateTime endTime,
    String sourceCalendar,
    boolean systemGenerated,
    String origin
) {

    private static final String TYPE_TIME_BLOCK = "TIME_BLOCK";
    private static final String STATUS_DONE = "DONE";
    private static final String ORIGIN_PLANNER = "PLANNER";

    /**
     * Whether the external entity mirroring this executable is a <b>record of time that already
     * passed</b> rather than an open item on a list — and must therefore <b>survive</b> completion
     * instead of being removed along with it.
     *
     * <p>Completing an executable normally deletes its Apple counterpart, so the satellites do not
     * accumulate checked-off reminders. Two shapes do not follow that rule, for the same reason:
     * <ul>
     *   <li>a {@code TIME_BLOCK} (ADR-039): its EKEvent is the time accounting of the block, and
     *       settling the block is precisely when that accounting becomes final;
     *   <li>an <b>observed episode</b> — a recorded nap and anything else the system writes after
     *       watching it happen: it is born {@code DONE} over the window it really occupied, so
     *       deleting on completion would delete it at birth and it would never reach the calendar.
     * </ul>
     *
     * @return true when completion must keep the external entity, false when it must remove it
     */
    public boolean isTimeRecord() {
        return TYPE_TIME_BLOCK.equals(type) || isObservedEpisode();
    }

    /**
     * An episode the system recorded after the fact, identified by the state such a row carries:
     * the planner's own {@code origin}, already {@code DONE}, and explicitly meant for the
     * satellites ({@code system_generated = false}).
     *
     * <p>That triple is what "born {@code DONE}" reduces to at read time, where only current state
     * is visible. It is precise because {@code origin} is written by nobody else — not by the sync
     * pipeline, not by a user edit: the only writer that stamps {@code PLANNER} on something that
     * is not a {@code TIME_BLOCK} is the recorder of observed episodes, and it inserts them already
     * completed. An {@code ACTIVITY} the user creates and finishes later carries no {@code origin}
     * at all, so it keeps the ordinary delete-on-completion behaviour.
     *
     * <p>A settled {@code PLANNER} block satisfies this too, harmlessly: {@link #isTimeRecord()}
     * has already claimed it by type, for the very same reason.
     */
    private boolean isObservedEpisode() {
        return ORIGIN_PLANNER.equals(origin)
            && STATUS_DONE.equals(status)
            && !systemGenerated;
    }
}
