package com.hyperbrain.planner.domain.model;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.UUID;

/**
 * A proposed {@code core_time_block} the generator places in the day, before persistence. Carries a
 * human-readable {@code reason} (legibilidad obligatoria — every block explains why it is there) and
 * the {@code wig} / {@code highLoad} flags the {@code AgendaValidator} re-checks against the walls
 * and the F6 quota. Persisted as {@code PLANNED} with {@code origin = PLANNER} once validated.
 *
 * <p><b>Membership (ADR-027 D1/D2).</b> The block is a <em>time container</em> that references N
 * executables. {@link #executableId()} is the block's <b>anchor</b> member — the executable the block
 * is built around, persisted on {@code core_time_block.executable_id}; {@code additionalMembers}
 * carries the rest of the theme. The full membership is projected onto {@code core_time_block_member}
 * and is <b>never</b> what identifies the block: identity is a persisted surrogate reconciled by
 * anchoring ({@link PlannerBlockIdentity}), so a member entering or leaving the theme can never
 * regenerate the block id.
 *
 * <p><b>WIG atomicity (ADR-027 D4).</b> A WIG block is atomic: it never groups other executables, so
 * {@code additionalMembers} must be empty when {@code wig} is set.
 *
 * <p><b>Theme.</b> The container's name is generated by the LLM (ADR-029) and lands on
 * {@code core_time_block.theme}. It is a presentation property <b>of the block</b> — it is never
 * written onto an executable's canonical title (ADR-012 mirror hygiene). The deterministic floor
 * leaves it null: {@code SchedulableExecutable} carries no display name, and forcing an extra read
 * just to derive a theme would buy nothing (the write-back already falls back to the anchor's name).
 *
 * @param executableId      the anchor executable this block schedules; never null
 * @param start             the block start instant; never null
 * @param end               the block end instant; never null, strictly after {@code start}
 * @param wig               true for the reserved WIG block (F1) — never expellable by energy nor validator
 * @param highLoad          true when the executable is high-load (counts against the F6 quota)
 * @param reason            the readable placement reason; never blank
 * @param additionalMembers the non-anchor members of the themed block, in presentation order; never
 *                          null (empty for a single-executable block), never containing the anchor,
 *                          nulls nor duplicates, and always empty for a WIG block
 * @param memberEfforts     each member's own remaining effort in minutes, aligned index-by-index with
 *                          {@link #members()} (anchor first); the apportionment weights
 *                          {@link #memberPlannedMinutes()} distributes the block duration by, so a
 *                          member's imputed minutes track its <em>own</em> effort rather than an even
 *                          share (ADR-013/ADR-027 D2, ADR-034). Null defaults to equal weights (the
 *                          pre-grouping even split); never contains a negative value
 * @param theme             the container's theme; null on the deterministic floor (blank is
 *                          normalized to null)
 */
public record AgendaBlock(
    UUID executableId,
    OffsetDateTime start,
    OffsetDateTime end,
    boolean wig,
    boolean highLoad,
    String reason,
    List<UUID> additionalMembers,
    List<Integer> memberEfforts,
    String theme
) {

    public AgendaBlock {
        if (executableId == null) {
            throw new IllegalArgumentException("executableId must not be null");
        }
        if (start == null || end == null) {
            throw new IllegalArgumentException("start and end must not be null");
        }
        if (!end.isAfter(start)) {
            throw new IllegalArgumentException("end must be strictly after start: " + start + " .. " + end);
        }
        if (reason == null || reason.isBlank()) {
            throw new IllegalArgumentException("reason must not be blank");
        }
        List<UUID> members =
            additionalMembers == null ? List.of() : new ArrayList<>(additionalMembers);
        if (members.contains(null)) {
            throw new IllegalArgumentException("additionalMembers must not contain null");
        }
        if (members.contains(executableId) || new LinkedHashSet<>(members).size() != members.size()) {
            throw new IllegalArgumentException(
                "additionalMembers must be distinct and must not repeat the anchor: " + members);
        }
        if (wig && !members.isEmpty()) {
            throw new IllegalArgumentException("a WIG block is atomic and must not group other executables");
        }
        additionalMembers = List.copyOf(members);

        int memberCount = additionalMembers.size() + 1;
        List<Integer> efforts = memberEfforts == null
            ? equalWeights(memberCount)
            : new ArrayList<>(memberEfforts);
        if (efforts.size() != memberCount) {
            throw new IllegalArgumentException(
                "memberEfforts must have one entry per member (" + memberCount + "): " + efforts);
        }
        if (efforts.stream().anyMatch(e -> e == null || e < 0)) {
            throw new IllegalArgumentException("memberEfforts must be non-null and non-negative: " + efforts);
        }
        memberEfforts = List.copyOf(efforts);
        theme = theme == null || theme.isBlank() ? null : theme.strip();
    }

    /** Builds a single-executable, themeless block — the shape the deterministic floor produces. */
    public AgendaBlock(UUID executableId, OffsetDateTime start, OffsetDateTime end, boolean wig,
                       boolean highLoad, String reason) {
        this(executableId, start, end, wig, highLoad, reason, List.of(), null, null);
    }

    /** Builds a themeless block with an explicit membership and the even-split default effort weights. */
    public AgendaBlock(UUID executableId, OffsetDateTime start, OffsetDateTime end, boolean wig,
                       boolean highLoad, String reason, List<UUID> additionalMembers) {
        this(executableId, start, end, wig, highLoad, reason, additionalMembers, null, null);
    }

    /** Builds a themed block with an explicit membership and the even-split default effort weights. */
    public AgendaBlock(UUID executableId, OffsetDateTime start, OffsetDateTime end, boolean wig,
                       boolean highLoad, String reason, List<UUID> additionalMembers, String theme) {
        this(executableId, start, end, wig, highLoad, reason, additionalMembers, null, theme);
    }

    /**
     * Builds a themeless grouped block from an ordered membership (anchor first) and each member's own
     * effort — the shape the deterministic affinity grouper produces (ADR-027 D1/D2). The block duration
     * is the callers' responsibility (typically {@code Σ memberEfforts}); the theme is left null so it
     * degrades to the anchor's name until the LLM names it.
     *
     * @param members       the ordered membership, anchor first; never null nor empty
     * @param memberEfforts each member's own remaining effort in minutes, aligned with {@code members}
     * @param start         the block start instant; never null
     * @param end           the block end instant; never null, strictly after {@code start}
     * @param highLoad      true when the group carries a high-load member (F6 quota)
     * @param reason        the readable placement reason; never blank
     * @return the grouped block; never null
     */
    public static AgendaBlock grouped(List<UUID> members, List<Integer> memberEfforts,
                                      OffsetDateTime start, OffsetDateTime end, boolean highLoad,
                                      String reason) {
        if (members == null || members.isEmpty()) {
            throw new IllegalArgumentException("members must not be empty");
        }
        UUID anchor = members.get(0);
        List<UUID> additional = List.copyOf(members.subList(1, members.size()));
        return new AgendaBlock(anchor, start, end, false, highLoad, reason, additional, memberEfforts, null);
    }

    /**
     * Returns a copy of this block retimed to a new window, preserving its membership, effort weights
     * and theme. Used by the LLM arrangement path, where the model may move a block but never
     * re-compose it.
     *
     * @param newStart the new start instant; never null
     * @param newEnd   the new end instant; never null, strictly after {@code newStart}
     * @param newReason the reason to carry (the model's coach note, or the floor's); never blank
     * @return the retimed block; never null
     */
    public AgendaBlock retimed(OffsetDateTime newStart, OffsetDateTime newEnd, String newReason) {
        return new AgendaBlock(executableId, newStart, newEnd, wig, highLoad, newReason,
            additionalMembers, memberEfforts, theme);
    }

    /**
     * Returns a copy of this block carrying the given theme, preserving everything else. The LLM names
     * the container (ADR-029); a blank theme normalizes to null so the write-back falls back to the
     * anchor's name.
     *
     * @param newTheme the container's theme; may be null or blank (normalized to null)
     * @return the re-themed block; never null
     */
    public AgendaBlock withTheme(String newTheme) {
        return new AgendaBlock(executableId, start, end, wig, highLoad, reason,
            additionalMembers, memberEfforts, newTheme);
    }

    /**
     * @return the block's full membership, anchor first; never null, never empty, immutable
     */
    public List<UUID> members() {
        List<UUID> members = new ArrayList<>(additionalMembers.size() + 1);
        members.add(executableId);
        members.addAll(additionalMembers);
        return List.copyOf(members);
    }

    /** @return the block duration in minutes */
    public long durationMinutes() {
        return java.time.Duration.between(start, end).toMinutes();
    }

    /**
     * Splits the container's duration across its members <b>in proportion to each member's own
     * effort</b> (ADR-027 D2 — the fine-grained counterpart of the ADR-013 imputation), so a member's
     * imputed {@code planned_minutes} tracks the work it actually carries rather than an even share.
     * Using an even split mis-imputes {@code planned}/{@code actual_minutes} per executable and corrupts
     * both the remaining-effort loop (ADR-013) and the completion ledger (ADR-034); this apportions by
     * weight instead.
     *
     * <p>The split is exact: {@code Σ planned_minutes} always equals the block duration. It uses the
     * largest-remainder (Hamilton) method — floor each member's proportional share, then hand the leftover
     * minutes to the members with the largest fractional parts (ties broken by member order) — so the
     * result is a deterministic pure function of the block. When the effort weights are all equal (the
     * pre-grouping default) this reduces to the previous even split; when they are all zero it falls back
     * to an even split to avoid a division by zero.
     *
     * @return one planned-minutes share per member, aligned index-by-index with {@link #members()};
     *         never null, same size as {@code members()}, summing to {@link #durationMinutes()}
     */
    public List<Integer> memberPlannedMinutes() {
        int memberCount = memberEfforts.size();
        int total = (int) durationMinutes();
        long weightSum = memberEfforts.stream().mapToLong(Integer::longValue).sum();
        if (weightSum <= 0) {
            return evenSplit(total, memberCount);
        }

        // Floor each proportional share, tracking the fractional remainders to distribute the leftover.
        Integer[] shares = new Integer[memberCount];
        int assigned = 0;
        double[] remainders = new double[memberCount];
        for (int index = 0; index < memberCount; index++) {
            double exact = (double) total * memberEfforts.get(index) / weightSum;
            int floor = (int) Math.floor(exact);
            shares[index] = floor;
            remainders[index] = exact - floor;
            assigned += floor;
        }
        // Hand the leftover minutes to the largest fractional remainders, earliest member breaking ties.
        int leftover = total - assigned;
        List<Integer> order = new ArrayList<>(memberCount);
        for (int index = 0; index < memberCount; index++) {
            order.add(index);
        }
        order.sort((a, b) -> {
            int byRemainder = Double.compare(remainders[b], remainders[a]);
            return byRemainder != 0 ? byRemainder : Integer.compare(a, b);
        });
        for (int i = 0; i < leftover; i++) {
            int index = order.get(i);
            shares[index] = shares[index] + 1;
        }
        return List.of(shares);
    }

    /** An even split of {@code total} minutes across {@code memberCount} members, remainder to the front. */
    private static List<Integer> evenSplit(int total, int memberCount) {
        int share = total / memberCount;
        int remainder = total % memberCount;
        List<Integer> minutes = new ArrayList<>(memberCount);
        for (int index = 0; index < memberCount; index++) {
            minutes.add(index < remainder ? share + 1 : share);
        }
        return List.copyOf(minutes);
    }

    /** Equal apportionment weights (all 1) for a block whose per-member effort is not supplied. */
    private static List<Integer> equalWeights(int memberCount) {
        List<Integer> weights = new ArrayList<>(memberCount);
        for (int index = 0; index < memberCount; index++) {
            weights.add(1);
        }
        return weights;
    }
}
