package com.hyperbrain.planner.domain.model;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.UUID;

/**
 * A proposed {@code core_time_block} the generator places in the day, before persistence. Carries a
 * human-readable {@code reason} (legibilidad obligatoria — every block explains why it is there) and
 * the {@code wig} / {@code highLoad} flags the {@code AgendaValidator} re-checks against the walls
 * and the F6 quota. Persisted as {@code PLANNED} with {@code origin = PLANNER} once validated.
 *
 * <p><b>Membership (ADR-027 D1/D2).</b> The block is a <em>time container</em> that references N
 * executables. {@link #executableId()} is the block's <b>anchor</b> member — the executable the block
 * is built around, persisted on {@code core_time_block.executable_id}; {@code additionalMembers}
 * carries the rest of the theme. The full membership is projected onto {@code core_time_block_member}
 * and is <b>never</b> what identifies the block: identity is a persisted surrogate reconciled by
 * anchoring ({@link PlannerBlockIdentity}), so a member entering or leaving the theme can never
 * regenerate the block id.
 *
 * <p><b>WIG atomicity (ADR-027 D4).</b> A WIG block is atomic: it never groups other executables, so
 * {@code additionalMembers} must be empty when {@code wig} is set.
 *
 * <p><b>Theme.</b> The container's name is generated by the LLM (ADR-029) and lands on
 * {@code core_time_block.theme}. It is a presentation property <b>of the block</b> — it is never
 * written onto an executable's canonical title (ADR-012 mirror hygiene). The deterministic floor
 * leaves it null: {@code SchedulableExecutable} carries no display name, and forcing an extra read
 * just to derive a theme would buy nothing (the write-back already falls back to the anchor's name).
 *
 * @param executableId      the anchor executable this block schedules; never null
 * @param start             the block start instant; never null
 * @param end               the block end instant; never null, strictly after {@code start}
 * @param wig               true for the reserved WIG block (F1) — never expellable by energy nor validator
 * @param highLoad          true when the executable is high-load (counts against the F6 quota)
 * @param reason            the readable placement reason; never blank
 * @param additionalMembers the non-anchor members of the themed block, in presentation order; never
 *                          null (empty for a single-executable block), never containing the anchor,
 *                          nulls nor duplicates, and always empty for a WIG block
 * @param theme             the container's theme; null on the deterministic floor (blank is
 *                          normalized to null)
 */
public record AgendaBlock(
    UUID executableId,
    OffsetDateTime start,
    OffsetDateTime end,
    boolean wig,
    boolean highLoad,
    String reason,
    List<UUID> additionalMembers,
    String theme
) {

    public AgendaBlock {
        if (executableId == null) {
            throw new IllegalArgumentException("executableId must not be null");
        }
        if (start == null || end == null) {
            throw new IllegalArgumentException("start and end must not be null");
        }
        if (!end.isAfter(start)) {
            throw new IllegalArgumentException("end must be strictly after start: " + start + " .. " + end);
        }
        if (reason == null || reason.isBlank()) {
            throw new IllegalArgumentException("reason must not be blank");
        }
        List<UUID> members =
            additionalMembers == null ? List.of() : new ArrayList<>(additionalMembers);
        if (members.contains(null)) {
            throw new IllegalArgumentException("additionalMembers must not contain null");
        }
        if (members.contains(executableId) || new LinkedHashSet<>(members).size() != members.size()) {
            throw new IllegalArgumentException(
                "additionalMembers must be distinct and must not repeat the anchor: " + members);
        }
        if (wig && !members.isEmpty()) {
            throw new IllegalArgumentException("a WIG block is atomic and must not group other executables");
        }
        additionalMembers = List.copyOf(members);
        theme = theme == null || theme.isBlank() ? null : theme.strip();
    }

    /** Builds a single-executable, themeless block — the shape the deterministic floor produces. */
    public AgendaBlock(UUID executableId, OffsetDateTime start, OffsetDateTime end, boolean wig,
                       boolean highLoad, String reason) {
        this(executableId, start, end, wig, highLoad, reason, List.of(), null);
    }

    /** Builds a themeless block with an explicit membership. */
    public AgendaBlock(UUID executableId, OffsetDateTime start, OffsetDateTime end, boolean wig,
                       boolean highLoad, String reason, List<UUID> additionalMembers) {
        this(executableId, start, end, wig, highLoad, reason, additionalMembers, null);
    }

    /**
     * Returns a copy of this block retimed to a new window, preserving its membership and theme. Used
     * by the LLM arrangement path, where the model may move a block but never re-compose it.
     *
     * @param newStart the new start instant; never null
     * @param newEnd   the new end instant; never null, strictly after {@code newStart}
     * @param newReason the reason to carry (the model's coach note, or the floor's); never blank
     * @return the retimed block; never null
     */
    public AgendaBlock retimed(OffsetDateTime newStart, OffsetDateTime newEnd, String newReason) {
        return new AgendaBlock(executableId, newStart, newEnd, wig, highLoad, newReason,
            additionalMembers, theme);
    }

    /**
     * @return the block's full membership, anchor first; never null, never empty, immutable
     */
    public List<UUID> members() {
        List<UUID> members = new ArrayList<>(additionalMembers.size() + 1);
        members.add(executableId);
        members.addAll(additionalMembers);
        return List.copyOf(members);
    }

    /** @return the block duration in minutes */
    public long durationMinutes() {
        return java.time.Duration.between(start, end).toMinutes();
    }

    /**
     * Splits the container's duration across its members as evenly as possible, so
     * {@code Σ planned_minutes} of the persisted {@code core_time_block_member} rows always equals the
     * block's duration (ADR-027 D2 — the fine-grained counterpart of the ADR-013 imputation). The
     * remainder goes to the leading members, keeping the split a pure function of the block.
     *
     * @return one planned-minutes share per member, aligned index-by-index with {@link #members()};
     *         never null, same size as {@code members()}
     */
    public List<Integer> memberPlannedMinutes() {
        int memberCount = additionalMembers.size() + 1;
        int total = (int) durationMinutes();
        int share = total / memberCount;
        int remainder = total % memberCount;
        List<Integer> minutes = new ArrayList<>(memberCount);
        for (int index = 0; index < memberCount; index++) {
            minutes.add(index < remainder ? share + 1 : share);
        }
        return List.copyOf(minutes);
    }
}
