package com.hyperbrain.planner.domain.model;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

/**
 * A persisted {@code PLANNED} block re-read for the agenda write-back (HU-01b delivery slice). Unlike
 * {@link AgendaBlock} (a pre-persistence proposal) this carries the block's own {@code id} — the
 * identity under which the block is mapped to its Apple entity, kept distinct from the executables'
 * own mappings so a block and the work it schedules never collide in {@code sync_mappings}.
 *
 * <p><b>Themed container (ADR-027 D1/D2).</b> The block references <b>N members</b> and carries a
 * {@code theme}, the container's name generated by the LLM (ADR-029). The deterministic floor leaves
 * the theme null, in which case {@link #title()} falls back to the anchor member's name — so a
 * deterministic day reads on the calendar exactly as it did before the grouping landed.
 *
 * <p><b>The grouping does not nest.</b> EventKit exposes no subtasks (ADR-027 v2.1.0, docs#81), so
 * every member keeps its own Apple entity and the block is an {@code EKEvent} <em>container</em> that
 * merely lists its members in the note. Per-task checkability is preserved through each member's own
 * {@code EKReminder}; the per-task progress accounting of ADR-013 D4 is untouched.
 *
 * @param blockId the {@code core_time_block.id}; the write-back local id; never null
 * @param theme   the container's theme; may be null or blank on the deterministic floor
 * @param members the executables the block references, in {@code ord} order; never null nor empty
 * @param start   the block start instant; never null
 * @param end     the block end instant; never null, after {@code start}
 * @param reason  the readable placement reason persisted with the block; may be null
 */
public record PlannedBlockRecord(
    UUID blockId,
    String theme,
    List<PlannedBlockMember> members,
    OffsetDateTime start,
    OffsetDateTime end,
    String reason
) {

    public PlannedBlockRecord {
        if (blockId == null) {
            throw new IllegalArgumentException("blockId must not be null");
        }
        if (members == null || members.isEmpty()) {
            throw new IllegalArgumentException("members must not be empty");
        }
        members = List.copyOf(members);
        if (start == null || end == null) {
            throw new IllegalArgumentException("start and end must not be null");
        }
        if (!end.isAfter(start)) {
            throw new IllegalArgumentException("end must be after start: " + start + " .. " + end);
        }
    }

    /**
     * The title of the container's calendar event.
     *
     * @return the {@code theme} when the LLM named the container, else the anchor member's name —
     *         the floor's pre-grouping behaviour; never blank
     */
    public String title() {
        return theme != null && !theme.isBlank() ? theme.strip() : anchor().name();
    }

    /** @return the block's anchor member — the first one by {@code ord}; never null */
    public PlannedBlockMember anchor() {
        return members.get(0);
    }

    /** @return true when the block groups more than one executable under a theme */
    public boolean grouped() {
        return members.size() > 1;
    }
}
